# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
# Files stored in repository builder
  - package-ecosystem: "maven"
    directory: "/builder"
    commit-message:
      prefix: chore
      include: "scope"
    schedule:
      interval: "weekly"
# Files stored in repository super
  - package-ecosystem: "maven"
    directory: "/super"
    commit-message:
      prefix: chore
      include: "scope"
    schedule:
      interval: "weekly"
# Files stored in repository core
  - package-ecosystem: "maven"
    directory: "/core"
    commit-message:
      prefix: chore
      include: "scope"
    schedule:
      interval: "weekly"
# Files stored in repository ehconnector
  - package-ecosystem: "maven"
    directory: "/ehconnector"
    commit-message:
      prefix: chore
      include: "scope"
    schedule:
      interval: "weekly"
# Files stored in repository viewer
  - package-ecosystem: "maven"
    directory: "/viewer"
    commit-message:
      prefix: chore
      include: "scope"
    schedule:
      interval: "weekly"
# Files stored in repository datagenerator
  - package-ecosystem: "maven"
    directory: "/datagenerator"
    commit-message:
      prefix: chore
      include: "scope"
    schedule:
      interval: "weekly"
# Files stored in repository distribution
  - package-ecosystem: "maven"
    directory: "/distribution"
    commit-message:
      prefix: chore
      include: "scope"
    schedule:
      interval: "weekly"
# Workflow files stored in the default location of `.github/workflows`
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: ci
      include: "scope"
    schedule:
      interval: "weekly"